config/routes.rb
Rails.application.routes.draw do
  get 'conditions/index'
  get 'conditions/show'
  get 'conditions/new'
  get 'conditions/edit'
  devise_for :users
root to: "doctors#index"
  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  get 'patients/edit'
  resources :doctors do
    resources :patients
  end

  resources :patients do
    resources :conditions
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :patients
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :doctor
  has_many :conditions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_action :authenticate_user!
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController

  # GET /patients/1/conditions
  def index
    # Get the patient with id=1
    @patient = Patient.find(params[:patient_id])
    # Access all conditions for that patient
    @conditions = @patient.conditions
  end

  # GET /patients/1/conditions/2
  def show
    @patient = Patient.find(params[:patient_id])
    # Find a condition in patients 1 that has id=2
    @condition = @patient.conditions.find(params[:id])
  end

  # GET /patients/1/conditions/new
  def new
    @patient = Patient.find(params[:patient_id])
    # Associate a condition object with patient 1
    @condition = @patient.conditions.build
  end

  # POST /patients/1/conditions
  def create
    @patient = Patient.find(params[:patient_id])
    # Populate a condition associate with patient 1 with form data,# Patient will be associated with the condition
    # @condition = @patient.conditions.build(params.require(:condition).permit!)
    @condition = @patient.conditions.build(params.require(:condition).permit(:name, :severity, :remedies, :condition_type))
    if @condition.save
      redirect_to patient_condition_url(@patient, @condition)
    else
      render :action => "new"
    end
  end

  # GET /patients/1/conditions/2/edit
  def edit
    @patient = Patient.find(params[:patient_id])
    # Get condition id=2 for patient 1
    @condition = @patient.conditions.find(params[:id])
  end

  # PUT /patients/1/conditions/2
  def update
    @patient = Patient.find(params[:patient_id])
    @condition = Condition.find(params[:id])
    if @condition.update_attributes(params.require(:condition).permit(:name, :severity, :remedies, :condition_type))
      redirect_to patient_condition_url(@patient, @condition)
    else
      render :action => "edit"
    end
  end

  # DELETE /patients/1/conditions/2
  def destroy
    @patient = Patient.find(params[:patient_id])
    @condition = Condition.find(params[:id])
    @condition.destroy
    respond_to do |format|
      format.html {redirect_to patients_conditon_path(@patient)}
      format.xml {head :ok}
    end
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:firstname, :surname, :dob, :address, :phone, :email, :specialisation)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  # GET /doctors/1/patients
  def index
    # Get the doctor with id=1
    @doctor = Doctor.find(params[:doctor_id])
    # Access all patients for that doctor
    @patients = @doctor.patients
  end

  # GET /doctors/1/patients/2
  def show
    @doctor = Doctor.find(params[:doctor_id])
    # Find a patient in doctors 1 that has id=2
    @patient = @doctor.patients.find(params[:id])
  end

  # GET /doctors/1/patients/new
  def new
    @doctor = Doctor.find(params[:doctor_id])
    # Associate a patient object with doctor 1
    @patient = @doctor.patients.build
  end

  # POST /doctors/1/patients
  def create
    @doctor = Doctor.find(params[:doctor_id])
    # Populate a patient associate with doctor 1 with form data,# Doctor will be associated with the patient
    # @patient = @doctor.patients.build(params.require(:patient).permit!)
    @patient = @doctor.patients.build(params.require(:patient).permit(:firstname, :surname, :admission_date, :dob, :address, :phone, :email, :healthy, :notes))
    if @patient.save
      redirect_to doctor_patient_url(@doctor, @patient)
    else
      render :action => "new"
    end
  end

  # GET /doctors/1/patients/2/edit
  def edit
    @doctor = Doctor.find(params[:doctor_id])
    # Get patient id=2 for doctor 1
    @patient = @doctor.patients.find(params[:id])
  end

  # PUT /doctors/1/patients/2
  def update
    @doctor = Doctor.find(params[:doctor_id])
    @patient = Patient.find(params[:id])
    if @patient.update_attributes(params.require(:patient).permit(:firstname, :surname, :admission_date, :dob, :address, :phone, :email, :healthy, :notes))
      redirect_to doctor_patient_url(@doctor, @patient)
    else
      render :action => "edit"
    end
  end

  # DELETE /doctors/1/patients/2
  def destroy
    @doctor = Doctor.find(params[:doctor_id])
    @patient = Patient.find(params[:id])
    @patient.destroy
    respond_to do |format|
      format.html {redirect_to doctor_patients_path(@doctor)}
      format.xml {head :ok}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/conditions/_form.html.erb
<%= form_for([@patient, @condition]) do |f| %>

<% if @condition.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@condition.errors.count, "error")%> prohibited this condition from being saved:</h2>
    <ul>
      <% @condition.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= f.label :Name, :for => 'condition_name' %>
    <%= f.text_field :name, :class => 'mdl-textfield__input', :id => 'condition_name', :type => 'text' %>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= f.label :Severity, :for => 'condition_severity' %>
    <%= f.text_field :severity, :class => 'mdl-textfield__input', :id => 'condition_severity', :type => 'text' %>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= f.label :Remedies, :for => 'condition_remedies' %><br/>
    <%= f.text_field :remedies, :class => 'mdl-textfield__input', :id => 'condition_remedies', :type => 'text'  %>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= f.label :ConditionType, :for => 'condition_type' %><br/>
    <%= f.text_field :condition_type, :class => 'mdl-textfield__input', :id => 'condition_type', :type => 'text' %>
</div>

<br/>

<div class="actions">
  <%= f.submit "Add/Update Details", :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
</div>

<br/>
<br/>
<% end %>

app/views/conditions/edit.html.erb
<h1>Editing Condition: <%= @condition.name %> </h1>

<%= render 'form' %>

<%= link_to 'Discard changes', patient_condition_path(@patient, @condition), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'Back', :back, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'All conditions', patient_conditions_path(@patient), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

app/views/conditions/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @patient.firstname %> <%= @patient.surname %>'s Conditions</h1>

<table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
  <tr>
      <th>Name</th>
      <th>Severity</th>
      <th>Medication</th>
      <th>Type</th>
      <th colspan="4"></th>
  </tr>

  <% for condition in @conditions %>

  <tr>
    <td><%= condition.name %></td>
    <td><%= condition.severity %></td>
    <td><%= condition.remedies %></td>
    <td><%= condition.condition_type %></td>
    <td></td>
    <td><%= link_to 'Details', patient_condition_path(@patient, condition), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
    <td><%= link_to 'Edit', edit_patient_condition_path(@patient, condition), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
    <td><%= link_to 'Delete', patient_condition_path(@patient, condition), method: :delete, data: { confirm: 'Are you sure you want to delete this condition?' }, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
  </tr>
  <% end %>
</table>

<br/>

<%= link_to 'Add New Condition', new_patient_condition_path(@patient), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'Back to patient', @patients, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

app/views/conditions/new.html.erb
<h1>Add a new condition</h1>

<%= render 'form' %>

<%= link_to 'Discard changes', patient_conditions_path(@patient), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

app/views/conditions/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Condition: <%= @condition.name %></h1>

<!-- Simple list -->
<style>
.demo-list-item {
  width: 300px;
}
</style>

<ul class="demo-list-item mdl-list">
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Name:</strong>
      <%= @condition.name %>
  </li>
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Severity: </strong>
      <%= @condition.severity %></span>
    </li>
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Medication:</strong>
      <%= @condition.remedies %></span>
  </li>
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Type:</strong>
      <%= @condition.condition_type %>
  </li>
</ul>

<%= link_to 'Edit details', edit_patient_condition_path(@patient, @condition), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'Delete', patient_condition_path(@patient, @condition), method: :delete, data: { confirm: 'Are you sure you want to delete this condition?' }, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

<br/>

<hr/>

<%= link_to 'Back to home', doctors_path, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'Back to conditions', patient_conditions_path(@patient), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor: <%= @doctor.firstname %>  <%= @doctor.surname %></h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Discard changes', @doctor, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'Back', :back, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'All doctors', doctors_path, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Surname</th>
      <th>Date of Birth</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Specialisation</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
    <tr>
      <td><%= doctor.firstname%></td>
      <td><%= doctor.surname %></td>
      <td><%= doctor.dob %></td>
      <td><%= doctor.address %></td>
      <td><%= doctor.phone %></td>
      <td><%= doctor.email %></td>
      <td><%= doctor.specialisation %></td>
      <td></td>
      <td><%= link_to 'Details', doctor, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
      <td><%= link_to 'Edit', edit_doctor_path(doctor), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
      <td><%= link_to 'Delete', doctor, method: :delete, data: { confirm: 'Are you sure you want to delete this doctor?' }, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Doctor', new_doctor_path, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

<h1>Patients</h1>

<table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Surname</th>
      <th>Date of Birth</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Specialisation</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
    <tr>
      <td><%= doctor.firstname%></td>
      <td><%= doctor.surname %></td>
      <td><%= doctor.dob %></td>
      <td><%= doctor.address %></td>
      <td><%= doctor.phone %></td>
      <td><%= doctor.email %></td>
      <td><%= doctor.specialisation %></td>
      <td></td>
      <td><%= link_to 'Details', doctor, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
      <td><%= link_to 'Edit', edit_doctor_path(doctor), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
      <td><%= link_to 'Delete', doctor, method: :delete, data: { confirm: 'Are you sure you want to delete this doctor?' }, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Patient', new_doctor_path, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

<h1>Conditions</h1>

<table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Surname</th>
      <th>Date of Birth</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Specialisation</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
    <tr>
      <td><%= doctor.firstname%></td>
      <td><%= doctor.surname %></td>
      <td><%= doctor.dob %></td>
      <td><%= doctor.address %></td>
      <td><%= doctor.phone %></td>
      <td><%= doctor.email %></td>
      <td><%= doctor.specialisation %></td>
      <td></td>
      <td><%= link_to 'Details', doctor, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
      <td><%= link_to 'Edit', edit_doctor_path(doctor), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
      <td><%= link_to 'Delete', doctor, method: :delete, data: { confirm: 'Are you sure you want to delete this doctor?' }, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Condition', new_doctor_path, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

app/views/doctors/new.html.erb
<h1>Add a new doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Discard changes', doctors_path, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctor:  <%= @doctor.firstname %>  <%= @doctor.surname %> </h1>

<!-- Simple list -->
<style>
.demo-list-item {
  width: 300px;
}
</style>

<ul class="demo-list-item mdl-list">
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Date of Birth: </strong>
      <%= @doctor.dob %></span>
  </li>
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Address:</strong>
      <%= @doctor.address %></span>
  </li>
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Phone:</strong>
      <%= @doctor.phone %>
  </li>
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Email:</strong>
      <%= @doctor.email %>
  </li>
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Specialisation:</strong>
      <%= @doctor.specialisation %>
  </li>
</ul>

<%= link_to 'Edit details', edit_doctor_path(@doctor), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'Delete', @doctor, method: :delete, data: { confirm: 'Are you sure you want to delete this doctor?' }, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

<!-- Display the patients of the doctor -->
<h1>Patients of <%= @doctor.firstname %>  <%= @doctor.surname %> </h1>

<ul class="demo-list-item mdl-list">
  <% @doctor.patients.each do |patient| %>
    <li class="mdl-list__item">
      <span class="mdl-list__item-primary-content">
        <strong>Name:</strong>
        <%= patient.firstname %>
        <%= patient.surname %>
    </li>
  <% end %>
</ul>


<%= link_to 'Show Patient Info', doctor_patients_path(@doctor), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'Add New Patient', new_doctor_patient_path(@doctor), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

<br/>

<hr/>

<%= link_to 'Back to home', doctors_path, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

app/views/patients/edit.html.erb
<h1>Editing Patient: <%= @patient.firstname %>  <%= @patient.surname %></h1>

<%= render 'form' %>

<%= link_to 'Discard changes', doctor_patient_path(@doctor, @patient), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'Back', :back, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'All patients', doctor_patients_path(@doctor), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients of  <%= @doctor.firstname %> <%= @doctor.surname %></h1>

<table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
  <tr>
      <th>Firstname</th>
      <th>Surname</th>
      <th>Admisson Date</th>
      <th>Date of Birth</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Healty</th>
      <th>Notes</th>
      <th colspan="4"></th>
  </tr>

  <% for patient in @patients %>

  <tr>
    <td><%= patient.firstname %></td>
    <td><%= patient.surname %></td>
    <td><%= patient.admission_date %></td>
    <td><%= patient.dob %></td>
    <td><%= patient.address %></td>
    <td><%= patient.phone %></td>
    <td><%= patient.email %></td>
    <td><%= patient.healthy %></td>
    <td><%= patient.notes %></td>
    <td></td>
    <td><%= link_to 'Details', doctor_patient_path(@doctor, patient), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
    <td><%= link_to 'Edit', edit_doctor_patient_path(@doctor, patient), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
    <td><%= link_to 'Delete', doctor_patient_path(@doctor, patient), method: :delete, data: { confirm: 'Are you sure you want to delete this patient?' }, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %></td>
  </tr>
  <% end %>
</table>

<br/>

<%= link_to 'Add New Patient', new_doctor_patient_path(@doctor), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'Back to doctor', @doctor, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

app/views/patients/new.html.erb
<h1>Add a new patient</h1>

<%= render 'form' %>

<%= link_to 'Discard changes', doctor_patients_path(@doctor), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Patient: <%= @patient.firstname %>   <%= @patient.surname %></h1>

<!-- Simple list -->
<style>
.demo-list-item {
  width: 300px;
}
</style>

<ul class="demo-list-item mdl-list">
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Admission Date:</strong>
      <%= @patient.admission_date %>
  </li>
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Date of Birth: </strong>
      <%= @doctor.dob %></span>
    </li>
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Address:</strong>
      <%= @doctor.address %></span>
  </li>
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Phone:</strong>
      <%= @doctor.phone %>
  </li>
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Email:</strong>
      <%= @doctor.email %>
  </li>
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Health:</strong>
      <%= @patient.healthy %>
  </li>
  <li class="mdl-list__item">
    <span class="mdl-list__item-primary-content">
      <strong>Notes:</strong>
      <%= @patient.notes %>
  </li>
</ul>

<%= link_to 'Edit details', edit_doctor_patient_path(@doctor, @patient), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'Delete', doctor_patient_path(@doctor, @patient), method: :delete, data: { confirm: 'Are you sure you want to delete this patient?' }, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

<!-- Display the conditions of the patient -->
<h1><%= @patient.firstname %>  <%= @patient.surname %>'s Conditions</h1>

<ul class="demo-list-item mdl-list">
  <% @patient.conditions.each do |condition| %>
    <li class="mdl-list__item">
      <span class="mdl-list__item-primary-content">
        <strong>Name:</strong>
        <%= condition.name %>
    </li>
  <% end %>
</ul>

<%= link_to 'Show Condition Info', patient_conditions_path(@patient), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'Add New Condition', new_patient_condition_path(@patient), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>

<br/>

<hr/>

<%= link_to 'Back to home', doctors_path, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
<%= link_to 'Back to patients', doctor_patients_path(@doctor), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>